### PR TITLE
started writing blurb.

### PR DESCRIPTION
**Pull request by fredericpoitevin**
Hi, let's work on the blurb that defines the scope and vision of compSPI.

### CODE REVIEW

**Comment by kdd-ubc** [comment]
Notes from conversation with Nina and Fred:

- lower the entrance bar for those interested in developing new methods/testing new ideas (ex: not having to recode 3D Flex from scratch, easy to access data)
- Provide a basis for benchmarking methods (currently non-existent)
-  scikitlearn for modern reconstruction methods
-  Modular approach that allows to run CryoGan, CryoPose Net etc.
-  current focus on reconstruction/simulator (?) but other aspects of the image processing will be considered in the long term (?)

**Comment by geoffwoollard** [comment]
Some ideas after reading http://arxiv.org/abs/2112.03235

Goals of compSPI
* probe the limits of algorithms with simulated and empirical data
* allow development at both a 
  * high level of abstraction to explore deep learning architectures, inference algorithms, loss functions, constraints, problem-specific evaluation methods
  *  low level implementation to reduce bottlenecks, quantify probabilistic numerics, enable parallelization 

Design principles of comSPI
* ease the cycle between analytical work and high quality working code useable to the community
* understandable vocabulary for talking across disciplinary boundaries
* encourage the collaboration of creative synergy between domain experts, applied mathematicians, computer scientists, and experts in modelling and simulation
* for physics informed ML in compSPI
  * observational biases: data-based structures that reflect physical structure 
  * inductive biases: model-based structure that encodes prior assumptions of physical laws, symmetries
  * learn biases: encourages solutions that adhere to known physics through the choice of loss functions, constraints, and inference algorithms

**Comment by ninamiolane** [comment]
Also an idea of blurb on ioSPI:

ioSPI provides tools to read, write and convert biological imaging and shape data:
- from different formats (gemmi, mrc),
- for different imaging modalities (cryo em at the moment),
- at different scales (atomic models, electrostatic maps)
for researchers to explore and visualize data from structural biology.

**Comment by ninamiolane** [comment]
How about we put some of our hackathon's slides here? We would author them as CompSPI team, instead of Nina Miolane.

Currently, they are in a PR in ioSPI, but I do not think that putting them on ioSPI is the most appropriate:
https://github.com/compSPI/ioSPI/pull/78

**Comment by fredericpoitevin** [comment]
@ninamiolane I created this PR from `fredericpoitevin:scope` back when I was using my personal fork, but I deleted it since and work from the `compSPI` fork now. Let me create a new PR from `compSPI:scope` now and I'll move the content of this PR there. Sorry for the mess.

**Pull request closed without merging**
