### PR TITLE
Correction on fft shifts

### PR DESCRIPTION
**Pull request by axel-levy**
There was an error on fftshifts/ifftshifts on primal_to_fourier transformations (fourier_to_primal_2D(primal_to_fourier_2D(r)) != r for odd resolution, same in 3D).

### CODE REVIEW

**Comment by geoffwoollard** [comment]
Let's look deeper... can you suggest a test to catch this? It will also help clarify why it matters.

For instance, this test is passing in the previous/current version. (Your fix is as well)

```
n=128
rand_2d = torch.distributions.Normal(torch.zeros(n,n),1).sample()
rand_2d_f = primal_to_fourier_2D(rand_2d)
rand_2d_f_r = fourier_to_primal_2D(rand_2d_f)
assert torch.allclose(rand_2d,rand_2d_f_r.real,atol=1e-4)

rand_2d_f = torch.distributions.Normal(torch.zeros(n,n),1).sample() + 1j*torch.distributions.Normal(torch.zeros(n,n),1).sample()
rand_2d_f_r = fourier_to_primal_2D(rand_2d_f)
rand_2d_f_r_f = primal_to_fourier_2D(rand_2d_f_r)
assert torch.allclose(rand_2d_f,rand_2d_f_r_f,atol=1e-4)
```

**Review by fredericpoitevin — CHANGES_REQUESTED** [review]
If the current unit test fails to catch this, we need to make a better one: is the tolerance in torch.allclose() stringent enough?

**Comment by geoffwoollard** [comment]
The old code fails with odd number of pixels, but Axel's fix passes this case. He mentioned this yesterday...

**Comment by geoffwoollard** [comment]
I can tighten up the tolerance to `atol=1e-5`. It passes 1000 times with different test data. But it fails sometimes at 1e-6, so let's keep it at that.

**Comment by geoffwoollard** [comment]
Ok tests passing. I think it's ready to merge.

**Review by geoffwoollard — APPROVED** [review]

**Review by fredericpoitevin — APPROVED** [review]

**Comment by geoffwoollard** [comment]
Since @fredericpoitevin approved, I will merge.

**Pull request merged**
